version: 2

jobs:
  checkout_and_install_deps:
    docker:
      - image: condaforge/linux-anvil
        entrypoint: /opt/docker/bin/entrypoint
        
    steps:
      - checkout:
          path: /home/conda/gopath/src/github.com/janelia-flyem/dvid
         
      - restore_cache:
          keys:
            - conda-tree-{{ arch }}-{{ checksum "/home/conda/gopath/src/github.com/janelia-flyem/dvid/scripts/conda-recipe/meta.yaml" }}

      - run:
          name: Setup conda environment
          environment:
            GOPATH: /home/conda/gopath
            DVID_SRC: /home/conda/gopath/src/github.com/janelia-flyem/dvid
          command: |
            ls -l /opt/docker/bin/
            whoami
            source /opt/docker/bin/entrypoint_source
            echo "Hi 1"
            conda config --add channels flyem-forge
            echo "Hi 2"
            conda create -n dvid-test || true
            echo "Hi 3"
            source activate dvid-test
            echo "Hi 4"
            cd ${DVID_SRC}
            echo "Hi 5"
            ./scripts/install-developer-dependencies.sh
            echo "Hi 6"

      - save_cache:
          key: conda-tree-{{ arch }}-{{ checksum "/home/conda/gopath/src/github.com/janelia-flyem/dvid/scripts/conda-recipe/meta.yaml" }}
          paths:
            - /opt/conda

  build_and_test:
    docker:
      - image: condaforge/linux-anvil
        entrypoint: /opt/docker/bin/entrypoint
    steps:
      - run:
          name: Build and test
          environment:
            GOPATH: /home/conda/gopath
            DVID_SRC: /home/conda/gopath/src/github.com/janelia-flyem/dvid
          command: |
            source /opt/docker/bin/entrypoint_source
            source activate dvid-test
            cd ${DVID_SRC}
            make dvid
            make test

workflows:
  version: 2
  setup_and_test:
    jobs:
      - checkout_and_install_deps
      - build_and_test:
          requires:
            - checkout_and_install_deps
